<a href="https://colab.research.google.com/github/abdulhamidll/Data-Science/blob/main/2_1_3_Arr_or_Pr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
xarr

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [16]:
# shart
cond = np.array([True, False, True, False, True])

In [18]:
result = np.where(cond, xarr, yarr)# cond == True bo'lsa xarr elementi, cond == False bo'lsa yarr elementi
result

array([1.1, 2.2, 1.3, 2.4, 1.5])

In [20]:
arr = np.random.randn(4, 4) # 4ta qator 4 ta ustunli 2 o'lchamli massiv yaratib olamiz
arr

array([[-0.15870297, -0.78236207, -0.29977142,  1.04152595],
       [-0.3714924 ,  0.52099226, -2.96756973,  1.16745181],
       [ 0.71653654,  0.06029607,  0.93767245,  0.64768707],
       [-0.01920908, -1.4532733 ,  0.17606736, -0.65988317]])

In [23]:
result2 = np.where(arr<0, -2, 2) # massivning manfiy elementalrini -2 ga musbat elementlarni 2 ga almashtiramiz
result2

array([[-2, -2, -2,  2],
       [-2,  2, -2,  2],
       [ 2,  2,  2,  2],
       [-2, -2,  2, -2]])