<a href="https://colab.research.google.com/github/abdulhamidll/Data-Science/blob/main/2_2_1_Universal_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [15]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [19]:
arr1 = np.random.randn(6) # 6 ta elementdan iborat massiv
arr1

array([-2.13959341,  2.11460077, -2.30498616,  1.12577906,  1.07443159,
       -0.31631143])

In [22]:
kasr_qism, butun_qism = np.modf(arr1)
print(kasr_qism, butun_qism)

[-0.13959341  0.11460077 -0.30498616  0.12577906  0.07443159 -0.31631143] [-2.  2. -2.  1.  1. -0.]


In [24]:
np.sign(arr1)

array([-1.,  1., -1.,  1.,  1., -1.])

In [26]:
# 2 ta argument qabul qiladigan funksiyalar

In [30]:
arr2 = np.random.randn(6)
arr2

array([ 0.54309385, -1.05708169, -0.02327912,  0.89322926, -0.88260525,
        0.73406291])

In [32]:
arr3 = np.random.randn(6)
arr3

array([-0.51127606,  0.15051669, -0.40529862,  0.17701467,  1.17529597,
       -1.03208219])

In [34]:
np.add(arr2, arr3) # arr2 va arr3 ning elemenetlarini mos ravishda qo'shib beradi

array([ 0.03181779, -0.90656501, -0.42857775,  1.07024393,  0.29269073,
       -0.29801928])

In [36]:
arr2 + arr3 # arr2 va arr3 ning elemenetlarini mos ravishda qo'shib beradi

array([ 0.03181779, -0.90656501, -0.42857775,  1.07024393,  0.29269073,
       -0.29801928])

In [38]:
np.multiply(arr2, arr3) # arr2 va arr3 ning elemenetlarini mos ravishda ko'paytirib beradi



array([-0.27767089, -0.15910843,  0.009435  ,  0.15811468, -1.03732239,
       -0.75761326])

In [39]:
np.maximum(arr2, arr3) # arr2 va arr3 ni elementlarini taqqoslab mos ravishda kattasini qaytaradi

array([ 0.54309385,  0.15051669, -0.02327912,  0.89322926,  1.17529597,
        0.73406291])