<a href="https://colab.research.google.com/github/abdulhamidll/Data-Science/blob/main/2_data_type.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

arr1 = np.array([1, 2, 2], dtype=np.float64) # float64 ma'lumot turiga ega array
arr1


array([1., 2., 2.])

In [6]:
arr2 = np.array([2, 4, 45], dtype=np.int16) # int16 ma'lumot turiga ega array
arr2

array([ 2,  4, 45], dtype=int16)

In [8]:
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int16')

In [14]:
arr3 = np.array([89,23131312312313123, 4])
arr3

array([               89, 23131312312313123,                 4])

In [16]:
arr3.dtype

dtype('int64')

In [18]:
float_arr = arr3.astype(np.float64)
float_arr

array([8.90000000e+01, 2.31313123e+16, 4.00000000e+00])