<a href="https://colab.research.google.com/github/abdulhamidll/Data-Science/blob/main/4_Boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [5]:
names = np.array(["ali", "vali", "g'ani", "ali", "hasan", "husan", "kali"])
names

array(['ali', 'vali', "g'ani", 'ali', 'hasan', 'husan', 'kali'],
      dtype='<U5')

In [12]:
data = np.random.randn  (7, 4)
data

array([[ 1.46530149, -0.4561718 , -1.33099004,  0.61602801],
       [-0.62317566, -0.89193006, -2.28147451, -0.29055363],
       [ 0.71175435,  0.39124982, -0.02107014, -0.3754167 ],
       [ 0.7646069 ,  1.08863583,  0.21334178,  0.01923973],
       [-1.89852777, -1.14109069,  0.41885932, -0.48869505],
       [-0.25350947, -0.37071421,  0.72203068,  0.73640922],
       [ 2.12428263, -1.62115787,  0.16583807,  0.67992935]])

In [14]:
names == "ali"

array([ True, False, False,  True, False, False, False])

In [16]:
data[ names == "ali"]

array([[ 1.46530149, -0.4561718 , -1.33099004,  0.61602801],
       [ 0.7646069 ,  1.08863583,  0.21334178,  0.01923973]])

In [18]:
data[names == "ali", 2:]# Aliga tegishli oxirgi ikkita ustunni ajratib olish  

array([[-1.33099004,  0.61602801],
       [ 0.21334178,  0.01923973]])

In [21]:
data[names != "ali"] # ( != )Alidan tashqari barcha malumotlarni ajratib olish

array([[-0.62317566, -0.89193006, -2.28147451, -0.29055363],
       [ 0.71175435,  0.39124982, -0.02107014, -0.3754167 ],
       [-1.89852777, -1.14109069,  0.41885932, -0.48869505],
       [-0.25350947, -0.37071421,  0.72203068,  0.73640922],
       [ 2.12428263, -1.62115787,  0.16583807,  0.67992935]])

In [27]:
data[~(names=="ali")]  # (~)Alidan tashqari barcha malumotlarni ajratib olish

array([[-0.62317566, -0.89193006, -2.28147451, -0.29055363],
       [ 0.71175435,  0.39124982, -0.02107014, -0.3754167 ],
       [-1.89852777, -1.14109069,  0.41885932, -0.48869505],
       [-0.25350947, -0.37071421,  0.72203068,  0.73640922],
       [ 2.12428263, -1.62115787,  0.16583807,  0.67992935]])

In [30]:
data[(names == "ali") | (names=="vali")]

array([[ 1.46530149, -0.4561718 , -1.33099004,  0.61602801],
       [-0.62317566, -0.89193006, -2.28147451, -0.29055363],
       [ 0.7646069 ,  1.08863583,  0.21334178,  0.01923973]])

In [34]:
data[data<0] = 0
data

array([[1.46530149, 0.        , 0.        , 0.61602801],
       [0.        , 0.        , 0.        , 0.        ],
       [0.71175435, 0.39124982, 0.        , 0.        ],
       [0.7646069 , 1.08863583, 0.21334178, 0.01923973],
       [0.        , 0.        , 0.41885932, 0.        ],
       [0.        , 0.        , 0.72203068, 0.73640922],
       [2.12428263, 0.        , 0.16583807, 0.67992935]])