<a href="https://colab.research.google.com/github/abdulhamidll/Data-Science/blob/main/5_Transposing%26Swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [4]:
arr = np.arange(6).reshape(3, 2) # arr massiv : Elemantlari 0-6gacha , shape(3,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
arr.T # arr massivni Transpos qilib beradi

array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
arr.swapaxes(1, 0)

array([[0, 2, 4],
       [1, 3, 5]])

In [11]:
np.dot(arr, arr.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])