<a href="https://colab.research.google.com/github/abdulhamidll/Data-Science/blob/main/Arifmetik_ammallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
#data
arr1 = np.arange(6).reshape(2, 3)# 0-6 elementlardan tashkil topgan array
arr2 = np.arange(6, 12).reshape(2, 3)# 6-12 elementlardan tashkil topgan array

In [6]:

arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
# ko'paytirish
arr1*arr2 # arr1 ning elementlarini arr2 ning elementlariga ko'paytirib beradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [11]:
arr1/arr2 # arr1 ning elementlarini arr2 ning elementlariga bo'lib beradi

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [13]:
arr1 + arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [14]:
arr1 - arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [15]:
arr1 ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25]])