<a href="https://colab.research.google.com/github/abdulhamidll/Data-Science/blob/main/Fayllar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.save("data", arr)

In [6]:
arr2 = np.load("data.npy")
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
np.savez("arrays", a=arr, b=arr1)

In [22]:
arrays = np.load("arrays.npz")
arrays

In [23]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
array_commpress = np.savez_compressed("array_commpress", a=arr, b=arr1)
array_commpress