<a href="https://colab.research.google.com/github/abdulhamidll/Data-Science/blob/main/Indexing%26Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
arr1 = np.arange(10, 100, 10)
arr1


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
arr1[3:5] # 3 dan 5 gacha bo'lgan elementlarni kesib olish

array([40, 50])

In [9]:
slic_arr = arr1[3:5]
slic_arr[:] = 0
slic_arr

array([0, 0])

In [11]:
arr1

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [15]:
arr2 = np.arange(10, 100, 10)
sliced_arr2 = arr2[3:5].copy()
sliced_arr2[:] = 0



In [17]:
arr2

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2d[2,2]

9

In [23]:
sliced_arr2d = arr2d[2, 0:2]
sliced_arr2d

array([7, 8])

In [32]:
sl_arr2d = arr2d[1:, 0:2]
sl_arr2d

array([[4, 5],
       [7, 8]])

In [35]:
arr3d = np.array([
                  [[1, 2, 3],
                   [4, 5, 6],
                   [8, 9, 0]],
                                  
                  [[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]],
                  
                  [[19, 20, 21],
                   [22, 23, 24],
                   [25, 36, 56]]

                  ])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 8,  9,  0]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 36, 56]]])

In [36]:
arr3d[0][1, 1]

5

In [39]:
arr3d[2][1:, 1:]

array([[23, 24],
       [36, 56]])