<a href="https://colab.research.google.com/github/abdulhamidll/Data-Science/blob/main/Math_and_stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# data
arr = np.random.randn(5, 4) # 5, 4 o'lchamli massiv (ramdom)
arr

array([[ 1.54612179,  0.64512334, -0.51165157,  0.26738949],
       [ 1.03501904,  0.17603994,  1.02314066,  0.22479204],
       [ 2.10553037, -0.68460316, -0.9600211 , -0.5841001 ],
       [ 0.9696956 ,  0.42167336,  0.37745657, -0.09459464],
       [-1.07703403, -0.66611874,  1.2996202 , -0.53600596]])

In [5]:
arr.sum() # arrayning barcha elementlari yig'indisini hisoblab beradi

4.977473103194595

In [7]:
np.sum(arr)  # arrayning barcha elementlari yig'indisini hisoblab beradi

4.977473103194595

In [9]:
arr.sum(axis=1) # qator bo'yicha yig'indi

array([ 1.94698306,  2.45899167, -0.12319398,  1.67423089, -0.97953854])

In [10]:
arr.sum(axis=0) # ustun bo'yicha yig'indi

array([ 4.57933277, -0.10788526,  1.22854476, -0.72251917])

In [12]:
#data
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [15]:
mean = np.sum(data)/len(data)
mean

2.0

In [17]:
np.mean(data)

2.0

In [20]:
data.mean()

2.0

In [22]:
arr

array([[ 1.54612179,  0.64512334, -0.51165157,  0.26738949],
       [ 1.03501904,  0.17603994,  1.02314066,  0.22479204],
       [ 2.10553037, -0.68460316, -0.9600211 , -0.5841001 ],
       [ 0.9696956 ,  0.42167336,  0.37745657, -0.09459464],
       [-1.07703403, -0.66611874,  1.2996202 , -0.53600596]])

In [25]:
np.mean(arr)

0.24887365515972976

In [28]:
np.mean(arr, axis=1) # qator bo'yicha o'rtacha qiymatni qaytaradi

array([ 0.48674576,  0.61474792, -0.0307985 ,  0.41855772, -0.24488463])

In [31]:
np.mean(arr, axis=0)

array([ 0.91586655, -0.02157705,  0.24570895, -0.14450383])

In [32]:
np.cumsum(data)

array([ 0,  1,  3,  6, 10])