<a href="https://colab.research.google.com/github/abdulhamidll/Data-Science/blob/main/Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr = np.random.randn(4) # 4 ta taxminiy elementlardan tashkil topgan massiv 
arr

array([-0.06815003,  0.37596861,  1.34768766,  0.46135558])

In [6]:
sorted_arr = np.sort(arr) # arr massiving tartiblangan elemntini qaytaradi
sorted_arr

array([-0.06815003,  0.37596861,  0.46135558,  1.34768766])

In [8]:
arr2 = -np.sort(-arr)
arr2

array([ 1.34768766,  0.46135558,  0.37596861, -0.06815003])

In [9]:
# 2D array (massiv)

arr2d = np.random.randn(2,4)
arr2d

array([[-0.6578806 , -0.31377418, -0.00502763,  1.76770124],
       [ 0.71534508,  1.43553547, -0.76559323,  0.67875833]])

In [10]:
# axis=0 qator 
row_sorted = np.sort(arr2d, axis=0) # 2d ning har bir qatori bo'yicha tartiblash
row_sorted

array([[-0.6578806 , -0.31377418, -0.76559323,  0.67875833],
       [ 0.71534508,  1.43553547, -0.00502763,  1.76770124]])

In [11]:
# axis=1 Ustun
col_sorted = np.sort(arr2d, axis=1) # arr2d ning har bir ustun bo'yicha tartiblash
col_sorted

array([[-0.6578806 , -0.31377418, -0.00502763,  1.76770124],
       [-0.76559323,  0.67875833,  0.71534508,  1.43553547]])