<a href="https://colab.research.google.com/github/abdulhamidll/Data-Science/blob/main/Unique.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
#data
names = np.array(['Sarvar', 'ali', 'bekorqul', 'shali', 'shali', 'bekorqul'])
ints = np.array([1, 2, 4, 3, 4, 2, 3, 6, 3])

In [6]:
np.unique(names) # takrorlanmas elemantlarni qaytaradi (takrorlansa ham faqat bittasini qabul qiladi)

array(['Sarvar', 'ali', 'bekorqul', 'shali'], dtype='<U8')

In [8]:
# in1d 
arr1 = np.array([1, 2, 1, 3, 4,5 ,2,3, 23,1, 32,2])
arr2 = np.array([1, 2, 3])

In [9]:
arr1

array([ 1,  2,  1,  3,  4,  5,  2,  3, 23,  1, 32,  2])

In [10]:
arr2

array([1, 2, 3])

In [12]:
np.in1d(arr1, arr2) # arr2 dagi elementlarni arr1da mavjudligini tekshirish

array([ True,  True,  True,  True, False, False,  True,  True, False,
        True, False,  True])

In [13]:
# setdiff1d
names1 = np.array(["hasan", "husan", "ali", "vali"])
names2 = np.array(["hasan", "alisher", "klai", "kali", "vali"])

In [14]:
np.setdiff1d(names1, names2) # names1 massivinig names2 qismidagi takrorlanmas qismini qaytaradi

array(['ali', 'husan'], dtype='<U5')